// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3PzGlhj8yqru-ozgGoAM9Fg-l6cJGcys',
    appId: '1:895904029591:web:2274059b6aae90428542d2',
    messagingSenderId: '895904029591',
    projectId: 'ktnsolutions-51d13',
    authDomain: 'ktnsolutions-51d13.firebaseapp.com',
    storageBucket: 'ktnsolutions-51d13.firebasestorage.app',
    measurementId: 'G-HP0SGS4609',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9nCIc9OIftVslw-xl8cmd6aUNdGa3N7Q',
    appId: '1:895904029591:android:7cf761f128b9c0af8542d2',
    messagingSenderId: '895904029591',
    projectId: 'ktnsolutions-51d13',
    storageBucket: 'ktnsolutions-51d13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBxiRr-61pMm5mCIQ6jXPgJ1z0aYaT0XI',
    appId: '1:895904029591:ios:f1e13ba4c706a8aa8542d2',
    messagingSenderId: '895904029591',
    projectId: 'ktnsolutions-51d13',
    storageBucket: 'ktnsolutions-51d13.firebasestorage.app',
    iosBundleId: 'com.ktnsolutions.ktnsolutions',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBxiRr-61pMm5mCIQ6jXPgJ1z0aYaT0XI',
    appId: '1:895904029591:ios:f1e13ba4c706a8aa8542d2',
    messagingSenderId: '895904029591',
    projectId: 'ktnsolutions-51d13',
    storageBucket: 'ktnsolutions-51d13.firebasestorage.app',
    iosBundleId: 'com.ktnsolutions.ktnsolutions',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3PzGlhj8yqru-ozgGoAM9Fg-l6cJGcys',
    appId: '1:895904029591:web:f2e6471814acb7fe8542d2',
    messagingSenderId: '895904029591',
    projectId: 'ktnsolutions-51d13',
    authDomain: 'ktnsolutions-51d13.firebaseapp.com',
    storageBucket: 'ktnsolutions-51d13.firebasestorage.app',
    measurementId: 'G-PN60WB8BNF',
  );

}